### PR TITLE
Support for Foundry V12.

### LINKED ISSUE #118: Support FoundryVTT v12
**Is your feature request related to a problem? Please describe.**
FoundryVTT has now released stable v12 (Build 324) but this module only supports v11.

**Describe the solution you'd like**
Please update this module to support v12.

**Additional context**
FoundryVTT v12 release notes: https://foundryvtt.com/releases/12.324

### PR DESCRIPTION
**Pull request by alessiocali**
I spent considerable time trying to figure out the project structure, I'm not a web dev expert but this should make the plugin compatible with V12 as far as I could see. The breaking changes were:

* `getAudioContext` was changed into `getAnalyzerContext`
* Some core labels for the ambient sound panel changed identifiers
* The AmbientSound window/application was completely revamped, I did some touch-ups to support the new structure including in the Svelte components. Not as pretty as Foundry's original but it will suffice for now.

Closes #118

### CODE REVIEW

**Comment by Morfedel** [comment]
> I spent considerable time trying to figure out the project structure, I'm not a web dev expert but this should make the plugin compatible with V12 as far as I could see. The breaking changes were:
> 
> * `getAudioContext` was changed into `getAnalyzerContext`
> * Some core labels for the ambient sound panel changed identifiers
> * The AmbientSound window/application was completely revamped, I did some touch-ups to support the new structure including in the Svelte components. Not as pretty as Foundry's original but it will suffice for now.
> 
> Closes #118

So, I'm ignorant on how github works, especially in conjunction with Foundry. How do you integrate these changes if they cant be auto updated in Foundry?

**Comment by ChunkLightTuna** [comment]
> > I spent considerable time trying to figure out the project structure, I'm not a web dev expert but this should make the plugin compatible with V12 as far as I could see. The breaking changes were:
> > 
> > * `getAudioContext` was changed into `getAnalyzerContext`
> > * Some core labels for the ambient sound panel changed identifiers
> > * The AmbientSound window/application was completely revamped, I did some touch-ups to support the new structure including in the Svelte components. Not as pretty as Foundry's original but it will suffice for now.
> > 
> > Closes #118
> 
> So, I'm ignorant on how github works, especially in conjunction with Foundry. How do you integrate these changes if they cant be auto updated in Foundry?

something like
```bash
 git clone git@github.com:alessiocali/fvtt-syrin-control.git
 cd fvtt-syrin-control
 npm install
 npm run build
 cp -R dist <YOUR DATA DIR>/modules/fvtt-syrin-control
 ```

**Comment by alessiocali** [comment]
> > I spent considerable time trying to figure out the project structure, I'm not a web dev expert but this should make the plugin compatible with V12 as far as I could see. The breaking changes were:
> > 
> > * `getAudioContext` was changed into `getAnalyzerContext`
> > * Some core labels for the ambient sound panel changed identifiers
> > * The AmbientSound window/application was completely revamped, I did some touch-ups to support the new structure including in the Svelte components. Not as pretty as Foundry's original but it will suffice for now.
> > 
> > Closes #118
> 
> So, I'm ignorant on how github works, especially in conjunction with Foundry. How do you integrate these changes if they cant be auto updated in Foundry?

Until the maintainer approves the pull requests and publishes an updated version, unfortunately the only option is what @ChunkLightTuna mentioned - that is clone my fork, build it locally and patch your foundry data manually.

**Comment by todimusprime** [comment]
Just as an FYI - (after stumbling through trying to figure out what i actually needed to install and build all this)  I have you fix installed and it appears to be working perfectly for me.

**Comment by frondeus** [comment]
Okay, as soon as the CI passes I will merge it and release new version

**Comment by alessiocali** [comment]
Mh. Something on jest, possibly due to the changes I had to apply on the passed jquery token from Foundry. I'll have a look

**Comment by alessiocali** [comment]
@frondeus The failure was indeed due to how I changed the AmbientSound component, it introduced a regression with respect to the V11 version. I fixed the regression but that still leaves the V12 version uncovered - I would need to change the fixture for that. If you don't mind I'd leave that for whoever takes the maintenance, this was more like a hotfix to not leave the community (...and myself tbqf :D ) without a V12 version.

**Comment by frondeus** [comment]
Yeah ok, merging :)

**Comment by frondeus** [comment]
I didnt test it, but i trust the community. New version has been released.

**Pull request merged**
